#!/usr/bin/env python

# ***
# Indirection for opening this version of Firefox with a specific profile
# ***

# Set USE_PROFILE to manually override what profile should be used.
# Leaving it blank will use the part of this file's name after BASE_NAME as the profile
USE_PROFILE = ""
BASE_NAME = "start_with_profile_"

import os
dirPath = os.path.dirname(__file__)
exPath  = (dirPath + '/firefox-bin').replace(' ', '\ ')

if len(USE_PROFILE) == 0:
    USE_PROFILE = __file__.rpartition(BASE_NAME)[2]

command = '%s -p "%s"' % (exPath, USE_PROFILE)
os.system(command)